service:
  name: contacts-crud-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline-sqs
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  createContact:
    handler: ./src/controllers/contacts.create
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - CreateContactQueue
              - Arn

resources:
  Resources:
    CreateContactQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: CreateContactQueue